export const SET_ORDER_BOOK_DATA = 'SET_ORDER_BOOK_DATA';
export const RESET_ORDER_BOOK_DATA = 'RESET_ORDER_BOOK_DATA';
export const SET_ASK_ORDER_BOOK_DATA='SET_ASK_ORDER_BOOK_DATA';
export const SET_BID_ORDER_BOOK_DATA='SET_BID_ORDER_BOOK_DATA';
export const SET_ORDER_BOOK_SOCKET_CREATED='SET_ORDER_BOOK_SOCKET_CREATED';